### ISSUE TITLE
Can't get .css and image files to work

### ISSUE THREAD

**Issue by prkiboy85** [dvdblk/custom-default-backend#1]
Hi, great work btw, but I have a problem, after doing everything, I have changed html files with my files, and css file with my one, but i cant get it to pull .css file and image from css folder. I have checked everythingm no solution, like nginx don't see the .css file and images? Even when I deploy yours files, yours .css file is not been shown, can you help? 

Thanks in advance

**Comment by dvdblk** [comment]
Hey man, just saw this sorry!

Is this still relevant or did you fix it?
